/**
 * Guard tests for the synthetic legacy fixtures (Task 1 / M1, slice 1).
 *
 * Why this file exists
 * ====================
 * Files written before schema 01.00.03 broke on save, and the reason nobody
 * noticed is that no test ever opened one. These fixtures close that gap.
 * They are generated by `scripts/generate-test-fixtures.py` from a blank
 * 01.00.04 template, downgraded to the schema Molio's real old files use.
 *
 * This file does NOT test the migration - it tests the fixtures themselves,
 * so that a regenerate-gone-wrong fails here rather than silently making the
 * migration tests pass against the wrong shape.
 *
 * The expectations below were measured on Molio's own sample files
 * (which cannot be committed here - see the script's header).
 */

import { describe, expect, it } from "vitest";

import type { MoliospecHandle } from "../src/index.js";
import { openMoliospec, readMoliospec } from "../src/index.js";
import { findAllSamples } from "./samples.js";

const samples = findAllSamples();

function fixture(version: string): string {
  const needle = `synthetic-legacy-${version.replace(/\./g, "-")}`;
  const hit = samples.find((s) => s.label.includes(needle));
  if (!hit) {
    throw new Error(
      `Legacy fixture for ${version} not found. Run: ` +
        `python3 scripts/generate-test-fixtures.py legacy`,
    );
  }
  return hit.path;
}

/** Table names present in the file. */
function tables(h: MoliospecHandle): string[] {
  const rows = h.db
    .prepare("select name from sqlite_master where type='table'")
    .all() as { name: string }[];
  return rows.map((r) => r.name);
}

/** Column names of one table, in declaration order. */
function columns(h: MoliospecHandle, table: string): string[] {
  const rows = h.db.pragma(`table_info(${table})`) as { name: string }[];
  return rows.map((r) => r.name);
}

/** The full 01.00.04 table list, for difference assertions. */
const TABLES_01_00_04 = [
  "attachment",
  "attachment_type",
  "construction_element_spec",
  "construction_element_spec_section",
  "contracts",
  "control_plan",
  "control_plan_section",
  "control_plan_section_header",
  "control_type_type",
  "custom_data",
  "project",
  "work_area_type",
  "work_spec",
  "work_spec_section",
];

describe("legacy fixtures", () => {
  it("all three are on disk and discoverable as samples", () => {
    for (const v of ["01.00.00", "01.00.01", "01.00.03"]) {
      expect(fixture(v)).toContain("synthetic-legacy");
    }
  });

  describe("01.00.03 - schema is already current", () => {
    it("stamps 01.00.03 but has the complete 01.00.04 schema", async () => {
      const h = await openMoliospec(fixture("01.00.03"));
      try {
        expect(readMoliospec(h).dbVersion).toBe("01.00.03");
        expect(tables(h).sort()).toEqual(TABLES_01_00_04);
        // The two columns that arrived with 01.00.03 / 01.00.04.
        expect(columns(h, "work_spec")).toContain("contract_id");
        expect(columns(h, "control_plan_section")).toContain("control_type");
      } finally {
        await h.close();
      }
    });
  });

  describe("01.00.01 - additively behind 01.00.04", () => {
    it("is missing exactly the two later tables", async () => {
      const h = await openMoliospec(fixture("01.00.01"));
      try {
        expect(readMoliospec(h).dbVersion).toBe("01.00.01");
        const missing = TABLES_01_00_04.filter((t) => !tables(h).includes(t));
        expect(missing.sort()).toEqual(["contracts", "control_type_type"]);
      } finally {
        await h.close();
      }
    });

    it("is missing exactly the four later columns", async () => {
      const h = await openMoliospec(fixture("01.00.01"));
      try {
        expect(columns(h, "work_spec")).not.toContain("contract_id");
        expect(columns(h, "control_plan_section")).not.toContain(
          "control_type",
        );
        expect(columns(h, "construction_element_spec")).not.toContain(
          "molio_construction_element_spec_revision_no",
        );
        expect(columns(h, "construction_element_spec")).not.toContain(
          "molio_construction_element_spec_revision_date",
        );
      } finally {
        await h.close();
      }
    });

    it("keeps control-plan links on the building element spec", async () => {
      const h = await openMoliospec(fixture("01.00.01"));
      try {
        const file = readMoliospec(h);
        const linked = file.constructionElementSpecs.filter(
          (b) => b.controlplan_design_id ?? b.controlplan_production_id,
        );
        expect(linked.length).toBe(2);
      } finally {
        await h.close();
      }
    });
  });

  describe("01.00.00 - structurally different", () => {
    it("is missing exactly the three later tables", async () => {
      const h = await openMoliospec(fixture("01.00.00"));
      try {
        expect(readMoliospec(h).dbVersion).toBe("01.00.00");
        const missing = TABLES_01_00_04.filter((t) => !tables(h).includes(t));
        // work_area_type is easy to miss: 01.00.00 has the *column* on
        // work_spec but not the lookup *table* it points at in 01.00.04.
        expect(missing.sort()).toEqual([
          "contracts",
          "control_type_type",
          "work_area_type",
        ]);
        expect(columns(h, "work_spec")).toContain("work_area_type");
      } finally {
        await h.close();
      }
    });

    it("uses the old column names project_key and control_plan.header", async () => {
      const h = await openMoliospec(fixture("01.00.00"));
      try {
        expect(columns(h, "project")).toContain("project_key");
        expect(columns(h, "project")).not.toContain("project_number");
        expect(columns(h, "project")).not.toContain("molio_referencelist_date");
        expect(columns(h, "control_plan")).toContain("header");
        expect(columns(h, "control_plan")).not.toContain("number_text");
        expect(columns(h, "construction_element_spec_section")).not.toContain(
          "pfbb_section_id",
        );
      } finally {
        await h.close();
      }
    });

    it("holds control-plan links on the work area, not the building element spec", async () => {
      const h = await openMoliospec(fixture("01.00.00"));
      try {
        expect(columns(h, "work_spec")).toContain("controlplan_design_id");
        expect(columns(h, "work_spec")).toContain("controlplan_production_id");
        const linked = h.db
          .prepare(
            "select count(*) as n from work_spec where " +
              "controlplan_design_id is not null or " +
              "controlplan_production_id is not null",
          )
          .get() as { n: number };
        // Two work areas, one link each - this is what the migration is
        // required to drop (decision: never guess which BDB owns it).
        expect(linked.n).toBe(2);
      } finally {
        await h.close();
      }
    });
  });

  describe("content is comparable across all three", () => {
    it("carries the same synthetic project in every version", async () => {
      for (const v of ["01.00.00", "01.00.01", "01.00.03"]) {
        const h = await openMoliospec(fixture(v));
        try {
          const file = readMoliospec(h);
          expect(file.workSpecs.length).toBe(2);
          expect(file.workSpecSections.length).toBe(6);
          expect(file.constructionElementSpecs.length).toBe(3);
          expect(file.constructionElementSpecSections.length).toBe(9);
          expect(file.controlPlans.length).toBe(2);
          expect(file.controlPlanSections.length).toBe(6);
          expect(file.attachments.length).toBe(1);
          // `contracts` is absent below 01.00.03; the reader returns [].
          expect(file.contracts.length).toBe(0);
        } finally {
          await h.close();
        }
      }
    });
  });
});
